version: '3'
services:
  # PHP 7.4 Apache
  app:
    image: ilkinabd/phalcon:4.1.2-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    working_dir: /var/www/html

  # MySQL Service
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    # volumes:
    # - ./dockerfiles/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: ilkinabd1
