<?php

use Phalcon\Forms\Element\Check;
use Phalcon\Forms\Element\Select;
use Phalcon\Forms\Form;
use Phalcon\Mvc\View;

/**
 * @var View $this
 * @var Form $form
 */
?>
<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Form Layout
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <!-- BEGIN: Form Layout -->
        <form class="intro-y box p-5" method="post">
            <?php
            $this->flash->output();
            foreach ($form->getElements() as $element): ?>
                <div class="mt-3">
                    <label for="<?= $element->getName() ?>" class="form-label">
                        <?= $element->getLabel() ?>
                    </label>
                    <?php
                    if ($element instanceof Check): ?>
                        <?= $element->render() ?>
                    <?php
                    elseif ($element instanceof Select): ?>
                        <?= $element->render(['class' => 'tom-select w-full']) ?>
                    <?php
                    else: ?>
                        <?= $element->render(['class' => 'form-control w-full']) ?>
                    <?php
                    endif ?>
                </div>
            <?php
            endforeach; ?>
            <div class="text-right mt-5">
                <button type="submit" class="btn btn-primary w-24">Save</button>
            </div>
        </form>
    </div>
</div>