<?php


namespace Vokuro\Forms;

use Phalcon\Forms\Element\Check;
use Phalcon\Tag;

class SwitchCheck extends Check
{
    public function render(array $attributes = array()): string
    {
        parent::render($attributes); // TODO: Change the autogenerated stub
        $html   = Tag::tagHtml('div', ['class' => 'mt-2']);
        $params = [
            'class' => 'form-check-switch',
            'name'  => $this->getName(),
            'id'    => $this->getName(),
            'value' => 'Y'
        ];
        if ($this->getValue() === 'Y') {
            $params['checked'] = true;
        }
        $html .= Tag::checkField($params);
        $html .= Tag::tagHtmlClose('div');

        return $html;
    }
}
