<?php

use Phalcon\Mvc\View;

/**
 * @var View $this
 */
?>
<!-- BEGIN: Modal Content -->
<div id="delete-modal-preview" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-21 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete these records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <form class="px-5 pb-8 text-center" method="post" id="delete-form"
                      action="/<?= $this->dispatcher->getControllerName() ?>/delete/[id]">
                    <button type="button" data-dismiss="modal"
                            class="btn btn-outline-secondary w-24 dark:border-dark-5 dark:text-gray-300 mr-1">Cancel
                    </button>
                    <button type="submit" class="btn btn-danger w-24">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- END: Modal Content -->