<?php

use Phalcon\Mvc\View;
use Phalcon\Paginator\RepositoryInterface;
use Vokuro\Models\Profiles;
use Vokuro\Models\Users;

/**
 * @var View                $this
 * @var RepositoryInterface $page
 */
$showed = count($page->getItems()) > 0 ? 'Showing 1 to '.$page->getLimit().' of '.$page->getTotalItems().' entries'
    : ' No items found'
?>
<h2 class="intro-y text-lg font-medium mt-10">
    Profiles Layout
</h2>
<?php
$this->flash->output(); ?>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="/profiles/create" class="btn btn-primary shadow-md mr-2">Add New Profile</a>
        <div class="hidden md:block mx-auto text-gray-600">
            <?=
            $showed ?>
        </div>
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <form class="w-56 relative text-gray-700 dark:text-gray-300" method="get" action="/users">
                <input type="text" class="form-control w-56 box pr-10 placeholder-theme-13" name="q"
                       placeholder="Search..." value="<?= $this->request->getQuery('q') ?>">
                <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i>
            </form>
        </div>
    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">NAME</th>
                <th class="text-center whitespace-nowrap">STATUS</th>
                <th class="text-center whitespace-nowrap">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var Profiles $profile */
            foreach ($page->getItems() as $profile): ?>
                <tr class="intro-x">
                    <td>
                        <a href="" class="font-medium whitespace-nowrap"><?= $profile->name ?></a>
                        <div class="text-gray-600 text-xs whitespace-nowrap mt-0.5"><?= $profile->id ?></div>
                    </td>
                    <td class="w-40">

                        <?php
                        if ($profile->active === 'Y'): ?>
                            <div class="flex items-center justify-center text-theme-20">
                                <i data-feather="check-square"
                                   class="w-4 h-4 mr-2"></i> Active
                            </div>
                        <?php
                        else: ?>
                            <div class="flex items-center justify-center text-theme-21">
                                <i data-feather="check-square"
                                   class="w-4 h-4 mr-2"></i> Inactive
                            </div>
                        <?php
                        endif; ?>
                    </td>
                    <td class="table-report__action w-56">
                        <div class="flex justify-center items-center">
                            <a class="flex items-center mr-3" href="/profiles/edit/<?= $profile->id ?>"> <i
                                        data-feather="check-square"
                                        class="w-4 h-4 mr-1"></i> Edit
                            </a>
                            <a class="flex items-center text-theme-21" href="javascript:;" data-delete
                               data-record-id="<?= $profile->id ?>"
                            > <i data-feather="trash-2"
                                 class="w-4 h-4 mr-1"></i>
                                Delete </a>
                        </div>
                    </td>
                </tr>
            <?php
            endforeach; ?>
            </tbody>
        </table>
    </div>
    <!-- END: Data List -->
    <?php
    $this->partial('pagination') ?>
</div>
